apiVersion: v1
kind: Service
metadata:
  labels:
    app: login-app
  name: login-app-service
spec:
  type: ClusterIP
  selector:
    app: login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
